include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore

linter:
  rules:
    - always_declare_return_types
    - avoid_print
    - avoid_unused_constructor_parameters
    - comment_references
    - directives_ordering
    - package_api_docs
    - prefer_const_constructors
    - prefer_final_fields
    - prefer_final_locals
    - prefer_relative_imports
    - public_member_api_docs
    - sort_constructors_first
    - unawaited_futures
